export const C = {
  primary: "#004e8a",
  primaryContainer: "#0066b2",
  primaryFixed: "#d3e4ff",
  surface: "#fcf9f6",
  surfaceContainerLowest: "#ffffff",
  surfaceContainerLow: "#f6f3f0",
  surfaceContainer: "#f0edea",
  surfaceContainerHigh: "#ebe8e5",
  surfaceContainerHighest: "#e5e2df",
  surfaceVariant: "#e5e2df",
  onSurface: "#1c1c1a",
  onSurfaceVariant: "#414751",
  outline: "#717782",
  outlineVariant: "#c1c7d3",
  error: "#ba1a1a",
  errorContainer: "#ffdad6",
  onErrorContainer: "#93000a",
  tertiary: "#7c3900",
  tertiaryFixed: "#ffdbc8",
  onTertiaryFixedVariant: "#743500",
  secondaryFixed: "#d3e4ff",
  onSecondaryFixedVariant: "#314866",
  secondary: "#49607f",
};

export const styles = {
  app: {
    fontFamily: "'Inter', sans-serif",
    background: C.surface,
    minHeight: "100vh",
    color: C.onSurface,
  },
  header: {
    position: "fixed", top: 0, left: 0, right: 0, zIndex: 50,
    height: 64,
    display: "flex", alignItems: "center", justifyContent: "space-between",
    padding: "0 24px",
    background: "rgba(255,255,255,0.88)",
    backdropFilter: "blur(12px)",
    borderBottom: `0.5px solid ${C.outlineVariant}40`,
    boxShadow: "0 1px 3px rgba(28,28,26,0.06)",
  },
  sidebar: {
    position: "sticky", top: 64,
    width: 240, minWidth: 240,
    height: "calc(100vh - 64px)",
    background: "#f8f7f4",
    borderRight: `0.5px solid ${C.outlineVariant}40`,
    padding: "20px 12px",
    display: "flex", flexDirection: "column",
  },
  mainContent: {
    flex: 1,
    padding: "40px 48px",
    maxWidth: 1200,
    margin: "0 auto",
    width: "100%",
  },
  card: {
    background: C.surfaceContainerLowest,
    borderRadius: 12,
    padding: "24px",
    boxShadow: "0px 12px 32px rgba(28,28,26,0.06)",
  },
  inputField: {
    width: "100%",
    background: C.surfaceContainerLow,
    border: "none",
    borderRadius: 8,
    padding: "12px 14px",
    fontSize: 13.5,
    color: C.onSurface,
    fontFamily: "'Inter', sans-serif",
    outline: "none",
    resize: "none",
    boxSizing: "border-box",
    transition: "box-shadow 0.15s",
  },
  select: {
    width: "100%",
    background: C.surfaceContainerLow,
    border: "none",
    borderRadius: 8,
    padding: "10px 12px",
    fontSize: 13.5,
    color: C.onSurface,
    fontFamily: "'Inter', sans-serif",
    outline: "none",
    cursor: "pointer",
    appearance: "none",
    backgroundImage: `url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='16' height='16' viewBox='0 0 24 24' fill='%23414751'%3E%3Cpath d='M7 10l5 5 5-5z'/%3E%3C/svg%3E")`,
    backgroundRepeat: "no-repeat",
    backgroundPosition: "right 10px center",
  },
  generateBtn: {
    width: "100%",
    padding: "14px 20px",
    background: "linear-gradient(135deg, #004e8a 0%, #0066b2 100%)",
    color: "#fff",
    border: "none",
    borderRadius: 8,
    fontSize: 16,
    fontWeight: 800,
    cursor: "pointer",
    display: "flex", alignItems: "center", justifyContent: "center", gap: 8,
    boxShadow: "0 6px 20px rgba(0,78,138,0.25)",
    transition: "filter 0.15s, transform 0.1s",
    fontFamily: "'Inter', sans-serif",
  },
  label: {
    fontSize: 10,
    fontWeight: 700,
    textTransform: "uppercase",
    letterSpacing: "0.08em",
    color: C.onSurfaceVariant,
    display: "block",
    marginBottom: 6,
    paddingLeft: 2,
  },
  outputToolbar: {
    display: "flex", alignItems: "center", justifyContent: "space-between",
    padding: "12px 16px",
    background: C.surfaceContainerLowest,
    borderBottom: `1px solid ${C.surfaceContainer}`,
  },
  toolbarBtn: {
    display: "flex", alignItems: "center", gap: 6,
    padding: "6px 12px",
    border: "none",
    borderRadius: 8,
    fontSize: 12,
    fontWeight: 700,
    cursor: "pointer",
    fontFamily: "'Inter', sans-serif",
    transition: "background 0.15s",
  },
  navItem: (active) => ({
    display: "flex", alignItems: "center", gap: 10,
    padding: "9px 14px",
    borderRadius: 8,
    fontSize: 13.5,
    fontWeight: active ? 600 : 400,
    color: active ? C.primary : C.onSurfaceVariant,
    background: active ? "#eff6ff" : "transparent",
    cursor: "pointer",
    border: "none",
    width: "100%",
    textAlign: "left",
    fontFamily: "'Inter', sans-serif",
    transition: "all 0.15s",
  }),
  histNavItem: (active) => ({
    display: "flex", alignItems: "center", gap: 10,
    padding: "10px 14px",
    borderRadius: active ? "8px 0 0 8px" : 8,
    fontSize: 11,
    fontWeight: active ? 700 : 500,
    color: active ? C.primary : C.onSurfaceVariant,
    background: active ? "#eff6ff" : "transparent",
    borderRight: active ? `3px solid ${C.primary}` : "none",
    cursor: "pointer",
    border: active ? `none` : "none",
    width: "100%",
    textAlign: "left",
    fontFamily: "'Inter', sans-serif",
    textTransform: "uppercase",
    letterSpacing: "0.06em",
    transition: "all 0.15s",
  }),
  topTab: (active) => ({
    background: "none",
    border: "none",
    borderBottom: active ? `2px solid ${C.primary}` : "2px solid transparent",
    paddingBottom: 4,
    fontSize: 13.5,
    fontWeight: active ? 600 : 400,
    color: active ? "#1d4ed8" : "#6b7280",
    cursor: "pointer",
    fontFamily: "'Inter', sans-serif",
    transition: "all 0.15s",
  }),
  statCard: (accent) => ({
    background: C.surfaceContainerLowest,
    borderRadius: 8,
    padding: "20px 24px",
    boxShadow: "0px 12px 32px rgba(28,28,26,0.06)",
    display: "flex", flexDirection: "column", justifyContent: "space-between",
    minHeight: 120,
  }),
  chip: (urgency) => {
    const map = {
      Critical: { bg: C.errorContainer, color: C.onErrorContainer, dot: C.error },
      High: { bg: C.tertiaryFixed, color: C.onTertiaryFixedVariant, dot: C.tertiary },
      Medium: { bg: C.secondaryFixed, color: C.onSecondaryFixedVariant, dot: C.secondary },
      Low: { bg: C.surfaceVariant, color: C.onSurfaceVariant, dot: C.outline },
    };
    const t = map[urgency] || map.Low;
    return {
      display: "inline-flex", alignItems: "center", gap: 6,
      padding: "4px 10px", borderRadius: 9999,
      background: t.bg, color: t.color,
      fontSize: 10, fontWeight: 700, textTransform: "uppercase",
      letterSpacing: "0.04em", dotColor: t.dot,
    };
  },
  moduleChip: {
    background: C.secondaryFixed,
    color: C.onSecondaryFixedVariant,
    padding: "2px 10px", borderRadius: 9999,
    fontSize: 10, fontWeight: 700, textTransform: "uppercase",
    letterSpacing: "0.04em",
  },
  filterChip: (active) => ({
    display: "inline-flex", alignItems: "center", gap: 6,
    padding: "6px 14px", borderRadius: 9999,
    background: active ? C.surfaceContainerHigh : "#f1f0ed",
    color: C.onSurface,
    fontSize: 11, fontWeight: 700, textTransform: "uppercase",
    letterSpacing: "0.05em",
    cursor: "pointer", border: "none",
    fontFamily: "'Inter', sans-serif",
    transition: "background 0.15s",
    boxShadow: active ? "inset 0 1px 3px rgba(0,0,0,0.06)" : "none",
  }),
};
